common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 25
  min_messages: warning

production:
  <<: *common
  database: dhdebates_production

development:
  <<: *common
  database: dhdebates_development

test:
  <<: *common
  database: dhdebates_test
