# Generate your secret key with "bundle exec rake secret"
development:
  secret_key_base:
  smtp_user:
  smtp_pass:
  contact_email_recipient: 'dhdebates@gmail.com'
  contact_email_from: 'noreply@dhdebates.gc.cuny.edu'

test:
  secret_key_base:
  smtp_user:
  smtp_pass:
  contact_email_recipient: 'dhdebates@gmail.com'
  contact_email_from: 'noreply@dhdebates.gc.cuny.edu'

production:
  secret_key_base:
  smtp_user:
  smtp_pass:
  contact_email_recipient: 'dhdebates@gmail.com'
  contact_email_from: 'noreply@dhdebates.gc.cuny.edu'
